name: Internal: Send WhatsApp Message

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
    secrets:
      WHAPI_TOKEN:
        required: true
      WHAPI_GROUP_ID:
        required: true

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
      WHAPI_GROUP_ID: ${{ secrets.WHAPI_GROUP_ID }}
      WHAPI_ACTION: ${{ inputs.action }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install requests
      - run: python send_whatsapp.py
