name: Internal - Send WhatsApp Message

on:
  workflow_call:
    inputs:
      action_type:
        required: true
        type: string
    secrets:
      WHAPI_TOKEN:
        required: true

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      WHATSAPP_GROUP_ID: ${{ vars.WHATSAPP_GROUP_ID }}
      WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
      ACTION_TYPE: ${{ inputs.action_type }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install requests
      - run: python send_whatsapp.py
