name: Lint and Typecheck

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      WHATSAPP_GROUP_ID: 'DUMMY_GROUP_ID'
      WHAPI_TOKEN: 'DUMMY_TOKEN'
      ACTION_TYPE: 'DUMMY_ACTION_TYPE'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: ruff check .
      - run: pyright .
      - run: pytest .
