name: Lint and Typecheck

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      WHATSAPP_GROUP_ID: 'DUMMY_GROUP_ID'
      WHAPI_TOKEN: 'DUMMY_TOKEN'
      ACTION_TYPE: 'DUMMY_ACTION_TYPE'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync --locked --all-groups
      - run: uv run ruff check .
      - run: uv run pyright .
      - run: uv run pytest .
