name: Send WhatsApp Poll

on:
  schedule:
    - cron: '0 5 * * 0-4' # 08:00 Israel Time (UTC+3)

jobs:
  call-reusable:
    uses: ./.github/workflows/_send-whatsapp.yml
    with:
      action: poll
    secrets:
      WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
      WHAPI_GROUP_ID: ${{ secrets.WHAPI_GROUP_ID }}
