name: Send WhatsApp Reminder

on:
  schedule:
    - cron: '30 8 * * 0-4' # 11:30 Israel Time (UTC+3)

jobs:
  call-reusable:
    uses: ./.github/workflows/_send-whatsapp.yml
    with:
      action: reminder
    secrets:
      WHAPI_TOKEN: ${{ secrets.WHAPI_TOKEN }}
      WHAPI_GROUP_ID: ${{ secrets.WHAPI_GROUP_ID }}
