---
name: Send WhatsApp Reminder

permissions: {}

on: # yamllint disable-line rule:truthy
  # switched to cron-job.org which is more reliable to avoid GitHub Actions delay time
  # schedule:
  # - cron: '55 8 * * 0-4' # 11:55 Israel Time (UTC+3)
  workflow_dispatch: # for testing via manual trigger

jobs:
  call-reusable:
    uses: ./.github/workflows/_send-whatsapp.yaml
    with:
      action_type: reminder
    secrets: inherit
