---
name: Weekly Dependency Upgrade

permissions: {}

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "5 6 * * 5" # Every Friday at 06:05 UTC
  workflow_dispatch: # Also allows manual triggering

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Upgrade locked dependencies
        run: uv lock --upgrade

      - name: Commit updated lockfile
        run: |
          git checkout -b chore/weekly-deps || git switch chore/weekly-deps
          git add uv.lock
          git commit -m "chore: weekly dependency upgrade [automated]" || echo "No changes to commit"

      - name: Push branch
        run: |
          git push --set-upstream origin chore/weekly-deps || echo "Branch already up-to-date"

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: weekly dependency upgrade [automated]"
          branch: chore/weekly-deps
          base: main
          title: "chore: Weekly Dependency Upgrade"
          body: |
            This PR was created automatically by the weekly workflow.
            It updates locked dependencies using `uv lock --upgrade`.
          labels: |
            dependencies
            automated
