---
name: Weekly Dependency Upgrade

permissions: {}

on:
  schedule:
    - cron: "5 6 * * 5" # Every Friday at 06:05 UTC
  workflow_dispatch: # Also allows manual triggering

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Upgrade locked dependencies
        run: uv lock --upgrade

      # Check if *any* files changed before creating PR
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create or update pull request
        id: cpr
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: weekly dependency upgrade [automated]"
          branch: chore/weekly-deps
          base: main
          title: "chore: Weekly Dependency Upgrade"
          body: |
            This PR was created automatically by the weekly workflow.
            It updates locked dependencies using `uv lock --upgrade`.
          delete-branch: false # Keep branch for reuse

      # Enable auto-merge for the created PR
      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
